---
- name: Ensure /tmp/kemhan directory exists on remote
  file:
    path: /tmp/kemhan
    state: directory
    mode: '0755'

- name: Ensure script exists on remote
  copy:
    src: system_report.sh
    dest: /tmp/kemhan/system_report.sh
    mode: '0755'

- name: Execute system report script
  shell: /tmp/kemhan/system_report.sh -ip {{ ansible_host }} -ad {{ inventory_hostname }}
  args:
    chdir: /tmp/kemhan
  register: report_result
  ignore_errors: yes

- name: Fetch report file to local
  fetch:
    src: "/tmp/kemhan/{{ item }}"
    dest: "{{ playbook_dir }}/../output/{{ group_names[0] }}/{{ inventory_hostname }}/"
    flat: yes
  with_items:
    - "{{ report_result.stdout_lines | select('match', 'sn\\..*_ip\\..*_.*_.*\\.txt') | list }}"
  when: report_result is defined

- name: Cleanup temporary files on remote
  file:
    path: "/tmp/kemhan/{{ item }}"
    state: absent
  with_items:
    - system_report.sh
    - "{{ report_result.stdout_lines | select('match', 'sn\\..*_ip\\..*_.*_.*\\.txt') | list }}"
  when: report_result is defined
  ignore_errors: yes